<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="RaJySaJaTuBhJa" failures="0" tests="2" name="Runner.TestRunner" time="23.046" errors="1" timestamp="07 Jul 2020 05:53:11 GMT" skipped="0">
  <testcase classname="Runner.TestRunner" name="scenario" time="0.211">
    <error message="Duplicate Keys not allowed. Duplicate for &#039;class StepDefinition.Stepdef&#039;" type="org.picocontainer.PicoCompositionException">
      <![CDATA[org.picocontainer.PicoCompositionException: Duplicate Keys not allowed. Duplicate for 'class StepDefinition.Stepdef'
	at org.picocontainer.DefaultPicoContainer.addAdapterInternal(DefaultPicoContainer.java:438)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:548)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:501)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:488)
	at cucumber.runtime.java.picocontainer.PicoFactory.start(PicoFactory.java:22)
	at cucumber.runtime.java.JavaBackend.buildWorld(JavaBackend.java:116)
	at cucumber.runner.Runner.buildBackendWorlds(Runner.java:155)
	at cucumber.runner.Runner.runPickle(Runner.java:78)
	at cucumber.api.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:84)
	at Runner.TestRunner.scenario(TestRunner.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- scenario -->
  <testcase classname="Runner.TestRunner" name="scenario" time="22.835"/>
</testsuite> <!-- Runner.TestRunner -->
